name: Kent Darr Ministries
favicon: null
layout_spectrum: 0.33334
typography_spectrum: 0.6519
title: Kent Darr Ministries
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#52240d'
    - '#c07a3e'
    - '#e7bb58'
    - '#ede5da'
  brandStrength: 0.1875
  lightness: 0.3125
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
