name: Kent Darr Ministries
favicon: null
layout_spectrum: 0.24982
typography_spectrum: 0.65418
title: Kent Darr Ministries
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#52240d'
    - '#c07a3e'
    - '#e7bb58'
    - '#ede5da'
  brandStrength: 0.3125
  lightness: 0.4375
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
