name: Kent Darr Ministries
favicon: null
layout_spectrum: 1
typography_spectrum: 0.68918
title: Kent Darr Ministries
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050304'
    - '#d5d1ce'
    - '#653430'
    - '#cf9081'
    - '#915c4e'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
